### ISSUE TITLE
files.ilastik.org is timing out

### ISSUE THREAD

**Issue by jni** [ilastik/ilastik.github.io#12]
Trying to click on http://files.ilastik.org/ilastik-1.1.8-OSX.zip results in a connection timeout error.

**Comment by akreshuk** [comment]
Thanks for your report. We are having server trouble since we had to move buildings on the weekend. I'll send you an alternative link later today.

**Comment by jni** [comment]
Thanks! =)

**Comment by akreshuk** [comment]
Here is the direct link to the Mac binary: https://www.dropbox.com/s/jl12tww60706z7j/ilastik-1.1.8-OSX.zip?dl=0
Let me know if there are any problems.

**Comment by jni** [comment]
Thanks @akreshuk! Working great. I'll let you close this once the website links are back up.

**Comment by k-dominik** [comment]
closing this, since we've moved our hosting and also provide mirrors now.
