### ISSUE TITLE
Second-level table of contents does not work

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik.github.io#13]
Just the word TOC is displayed instead of shortcuts to workflow descriptions in the Documentation section.

**Comment by stuarteberg** [comment]
I don't see the problem you're referring to.  Can you post a link to the specific page you're looking at?  FWIW, this is what I see on the Documentation main page:

![screen shot 2016-03-21 at 11 01 06 am](https://cloud.githubusercontent.com/assets/1655821/13922780/46d0799e-ef54-11e5-8f95-792bcbcc6729.png)

**Comment by akreshuk** [comment]
Ha, I tried to make a screenshot for you from the laptop, and here it works! I mean the items which open under "Pixel Classification"("How it works...", etc) are now visible. In the desktop Firefox I just see TOC there. I guess it depends on the browser.
![screenshot from 2016-03-21 18-03-03](https://cloud.githubusercontent.com/assets/901064/13927040/4080d648-ef8f-11e5-988b-0e8485bc4d25.png)

**Comment by akreshuk** [comment]
I still don't see the second level TOC and the open item is not present in the list at all. I have Firefox 47.0, is that too old?
![ilastik - pixel classification - mozilla firefox_007](https://cloud.githubusercontent.com/assets/901064/16450999/a18e8d4e-3e00-11e6-88ef-bad6c317c4cb.png)

**Comment by chaubold** [comment]
Same thing happens on Chrome and Safari on OSX 10.10, the sub-elements as well as the currently selected item are gone.

**Comment by chaubold** [comment]
@akreshuk do you know by any chance whether it ever worked since the switch to Jekyll 3? I didn't have any luck yet on finding where the `{:toc}` macro is coming from, or what changed...

**Comment by akreshuk** [comment]
The toc macro is in the _includes, but it also just runs some macro and adds <div>s to it. No idea when it stopped working, but March 21st it was still ok on my laptop at least.

**Comment by chaubold** [comment]
I've fixed at least the missing active top level heading. On to the second level...
