### ISSUE TITLE
Merge docs for the different tracking workflows

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik.github.io#29]
We currently have Tracking and `Tracking with Learning`, which are mostly duplicates of each other, and where various parts are outdated. Then there is the new `Animal Tracking` that already talks about some export plugins etc. We should merge the documentation and update it to match the latest release.

**Comment by k-dominik** [comment]
I'll close this, as it has been beautifully done by @Beinabih and @akreshuk
