### ISSUE TITLE
Documentation for Object Classification headless mode is outdated

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik.github.io#36]
as a user pointed out in https://github.com/ilastik/ilastik/issues/1590, the docs mention special command line flags for export (in addition to the `--export_source` ones. Depending on how we fix the bug, we should update the documentation. I suggest switching to the new command line syntax with `--export_source`.

**Comment by akreshuk** [comment]
i think consistency is important, so i'd also be in favor of --export_source
