### ISSUE TITLE
Slow download speeds

### ISSUE THREAD

**Issue by boazmohar** [ilastik/ilastik.github.io#88]
Not a huge issue, just a bit of a pain.
A download of any version form the website takes me a few hour if not a whole day. 

The spped of download is very fast to begin with (Estimated download in ~15min) but then it stops after downloading ~ 30-50% but regains speed after long intervals of nothing at all.
Any help with this would be appricated.
I have tried downloading from within my workplace (Janelia, Ashburn VA, USA) and my home network (also in Ahsburn).

Thanks!!

**Comment by k-dominik** [comment]
Hi @boazmohar,

thanks a lot for letting us know. I'll try to track it down.

Cheers!

**Comment by k-dominik** [comment]
hey, I'm closing this - we have added a second mirror for downloads now (but were not able to track down any reason for the sluggish downloads that were reported).
