### ISSUE TITLE
menu overlaps on "table-like" devices

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik.github.io#99]
The top menu seems to overlap page content under certain conditions. I've player around with it a bit and it seems to happen between a width of 770px and 1000px.

**Example Image**
![responsive](https://user-images.githubusercontent.com/24434157/59754865-40634a80-9287-11e9-822a-660c02d6c9e1.png)

**Comment by emilmelnikov** [comment]
This is because we have too many lenthy items in our navbar: https://getbootstrap.com/docs/3.4/components/#navbar-default
